#datasource
spring:
  datasource:
    url: jdbc:mysql://118.31.66.124:3306/shandianDB?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: kaifa
    password: xl098_qwe
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false

