#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cqrs?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    # 这个是配置模板路径的，默认就是templates，可不用配置
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5
  jackson:
    time-zone: GMT+8
    serialization:
      # 把日期转换成时间戳进行翻译
      WRITE_DATES_AS_TIMESTAMPS: true
  profiles:
    active: ${profileActive}
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
