#datasource
spring:
  datasource:
    url: jdbc:mysql://118.31.66.124:3306/shandianDB?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: kaifa
    password: xl098_qwe
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    # 这个是配置模板路径的，默认就是templates，可不用配置
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5
  jackson:
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  profiles:
    active: ${profileActive}
#mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: cn.xlteam.mapper


#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  row-bounds-with-count: countSql

parameter:
  weixin_openAppID: wxba65ef7d29f4b691
  weixin_openAppSecret: 0c213bd654eefe40cb5634d47126c912
  baidu_ak: ECb21afcec6ce368e6f919e1ed405c33
  #短信服务商(云片)
  send_mess_url : http://yunpian.com/v1/sms/send.json
  yp_api_key : bded5f9aaa9bc4364774ba295d8fa47e
  yp_template : 您的验证码是%s。如非本人操作，请忽略本短信
  #微信支付
  pay_api_key : hangzhoulangchengxinnengyuanyoux
  #商户号
  pay_mch_id : 1488760482

mapper:
  identity: MYSQL
  not-empty: false
  mappers:
    - cn.xlteam.mapper.ChargePriceMapper

server:
   context-path : /lighint
